FROM metabase/metabase:latest

# Add Trino JDBC driver
RUN curl -L https://github.com/starburstdata/metabase-driver/releases/download/6.1.0/starburst-6.1.0.metabase-driver.jar -o /plugins/starburst-6.1.0.metabase-driver.jar
