services:
  trino:
    container_name: trino
    build:
      context: ./trino
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Uncomment this if you want to use 'Bring your own Storage' with the Tableflow connector:
    # environment:
    #   - AWS_PROFILE=default
    #   - AWS_REGION=us-east-1
    #   - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-$(aws configure get aws_access_key_id)}
    #   - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-$(aws configure get aws_secret_access_key)}
    volumes:
      - $PWD/trino/catalog:/etc/trino/catalog
      - $PWD/trino/log.properties:/etc/trino/log.properties

  superset:
    init: true
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    volumes:
      - $PWD/storage/superset_home:/app/superset_home
    environment:
      - DATABASE_DB=superset
      - DATABASE_HOST=superset_db
      - DATABASE_PASSWORD=superset
      - DATABASE_USER=superset
      - DATABASE_PORT=5432
    ports:
      - '8088:8088'
    entrypoint: []
    command: >
      bash -c "
        if [ ! -f /app/superset_home/.setup_complete ]; then
          echo 'Running first-time setup...'
          superset db upgrade && \
          superset init && \
          superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@localhost --password secret && \
          touch /app/superset_home/.setup_complete && \
          echo 'Setup complete!'
        else
          echo 'Setup already completed, skipping...'
        fi &&
        exec /usr/bin/run-server.sh
      "

  superset_db:
    init: true
    image: postgres:alpine
    container_name: superset_db
    volumes:
      - $PWD/storage/superset_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=secretsecret
    ports:
      - '5432:5432'

  metabase:
    container_name: metabase
    build:
      context: ./metabase
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  metabase-run-setup:
    image: alpine:latest
    container_name: metabase-run-setup
    depends_on:
      - metabase
    volumes:
      - ./metabase/setup.sh:/setup.sh
    command: sh /setup.sh
